name: taoacr
recipe: drupal10
config:
  webroot: /web
  php: "8.1"
  composer_version: "2.2.18"
services:
  sbdb:
    type: mysql
    creds:
      user: drupal10
      password: drupal10
      database: drupal10
  appserver:
    build:
      - composer install
    overrides:
      environment:
        PHP_SENDMAIL_PATH: '/usr/sbin/sendmail -S mailhog:1025'
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
proxy:
  appserver:
    - taoacr.lndo.site
    - site-builder.lndo.site
  mailhog:
    - mailhog.taoacr.lndo.site

