name: taoacr
recipe: drupal9
config:
  webroot: /web
  php: "8.0"
  composer_version: "2.0.1"
services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://taoacr.lndo.site"
        PHP_SENDMAIL_PATH: '/usr/sbin/sendmail -S mailhog:1025'
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
proxy:
  mailhog:
    - mailhog.taoacr.lndo.site