_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: es
session:
  parameter: language
url:
  source: prefix
  prefixes:
    en: en
    es: es
    fr: fr
selected_langcode: site_default
